<?php
$config = array(
array('name' => 'Altar Brook Lair','pic_url' => 'gw2-altar-brook-lair-guild-treck.jpg','map' => 'Queensdale','way_point' => 'Crossing Waypoint','cnname' => '','code' => '[&BPIAAAA=]'),
array('name' => 'Anthem’s Hold','pic_url' => 'gw2-anthems-hold-guild-treck.jpg','map' => 'Cursed Shore','way_point' => 'Shipwreck Rock Waypoint','cnname' => '','code' => '[&BOQGAAA=]'),
array('name' => 'Anya\'s Patch','pic_url' => 'gw2-anyas-patch-guild-treck.jpg','map' => 'Diessa Plateau','way_point' => 'Nolan Waypoint','cnname' => '','code' => '[&BN4AAAA=]'),
array('name' => 'Arctodus Haunt','pic_url' => 'gw2-arctodus-haunt-guild-treck.jpg','map' => 'Wayfarer Foothills','way_point' => 'Vendrake\'s Homestead Waypoint','cnname' => '','code' => '[&BH4BAAA=]'),
array('name' => 'Backroot Fountain','pic_url' => 'gw2-backroot-fountain-guild-treck.jpg','map' => 'The Grove','way_point' => 'Reckoner\'s Waypoint','cnname' => '','code' => '[&BLsEAAA=]'),
array('name' => 'Badjelly Kelpbed','pic_url' => 'gw2-badjelly-kelpbed-guild-treck.jpg','map' => 'Snowden Drifts','way_point' => 'Exile Waypoint','cnname' => '','code' => '[&BLwAAAA=]'),
array('name' => 'Bandit\'s Cabbage Patch','pic_url' => 'gw2-bandits-cabbage-patch-guild-treck.jpg','map' => 'Harathi Hinterlands','way_point' => 'Wynchona Rally Point Waypoint','cnname' => '','code' => '[&BKgAAAA=]'),
array('name' => 'Beetlestone Mirador','pic_url' => 'gw2-beetlestone-mirador-guild-treck.jpg','map' => 'Queensdale','way_point' => 'Beetletun Waypoint','cnname' => '','code' => '[&BPoAAAA=]'),
array('name' => 'Black Lion Root Cellar','pic_url' => 'gw2-black-lion-root-cellar-guild-treck.jpg','map' => 'The Grove','way_point' => 'Reckoner\'s Waypoint','cnname' => '','code' => '[&BLsEAAA=]'),
array('name' => 'Blackblade Butte','pic_url' => 'gw2-blackblade-butte-guild-treck.jpg','map' => 'Diessa Plateau','way_point' => 'Font of Rhand Waypoint','cnname' => '','code' => '[&BNwAAAA=]'),
array('name' => 'Blasted Sepulchre','pic_url' => 'gw2-blasted-sepulchre-guild-treck.jpg','map' => 'Diessa Plateau','way_point' => 'Blasted Moors Waypoint','cnname' => '','code' => '[&BNoAAAA=]'),
array('name' => 'Blood Ooze Gallery','pic_url' => 'gw2-blood-ooze-gallery-guild-treck.jpg','map' => 'Bloodtide Coast','way_point' => 'Mournful Waypoint','cnname' => '','code' => '[&BK0BAAA=]'),
array('name' => 'Bluup’s Comeuppance','pic_url' => 'gw2-bluups-comeuppance-guild-treck.jpg','map' => 'Rata Sum','way_point' => 'Research Waypoint','cnname' => '','code' => '[&BLgEAAA=]'),
array('name' => 'Brandstrike Digs','pic_url' => 'gw2-brandstrike-digs-guild-treck.jpg','map' => 'Fields of Ruin','way_point' => 'Helliot Mine Waypoint','cnname' => '','code' => '[&BEsBAAA=]'),
array('name' => 'Briarthorn Barrier','pic_url' => 'gw2-briarthorn-barrier-guild-treck.jpg','map' => 'Caledon Forest','way_point' => 'Spiral Waypoint','cnname' => '','code' => '[&BDUBAAA=]'),
array('name' => 'Broken Falls Courtyard','pic_url' => 'gw2-broken-falls-courtyard-guild-treck.jpg','map' => 'Black Citadel','way_point' => 'Ruins of Rin Waypoint','cnname' => '','code' => '[&BKwDAAA=]'),
array('name' => 'Broodmother Falls','pic_url' => 'gw2-broodmother-falls-guild-treck.jpg','map' => 'Frostgorge Sound','way_point' => 'Yak\'s Bend Waypoint','cnname' => '','code' => '[&BIQCAAA=]'),
array('name' => 'Brother\'s Notch','pic_url' => 'gw2-brothers-notch-guild-treck.jpg','map' => 'Hoelbrak','way_point' => 'Hero\'s Compass Waypoint','cnname' => '','code' => '[&BJADAAA=]'),
array('name' => 'Burstbubble Blind','pic_url' => 'gw2-burstbubble-blind-guild-treck.jpg','map' => 'Blazeridge Steppes','way_point' => 'Tumok\'s Waypoint','cnname' => '','code' => '[&BPsBAAA=]'),
array('name' => 'Cache of the Pursued','pic_url' => 'gw2-cache-of-the-pursued-guild-treck.jpg','map' => 'Cursed Shore','way_point' => 'Caer Shadowfain Waypoint','cnname' => '','code' => '[&BCEDAAA=]'),
array('name' => 'Cademkrall Overlook','pic_url' => 'gw2-cademkrall-overlook-guild-treck.jpg','map' => 'Plains of Ashford','way_point' => 'Watchcrag Tower Waypoint','cnname' => '','code' => '[&BIgBAAA=]'),
array('name' => 'Canyonweb Cave','pic_url' => 'gw2-canyonweb-cave-guild-treck.jpg','map' => 'Blazeridge Steppes','way_point' => 'Brandview Waypoint','cnname' => '','code' => '[&BAQCAAA=]'),
array('name' => 'Captain\'s Berth','pic_url' => 'gw2-captains-berth-guild-treck.jpg','map' => 'Malchor\'s Leap','way_point' => 'Lights Waypoint','cnname' => '','code' => '[&BLICAAA=]'),
array('name' => 'Castavall Corner','pic_url' => 'gw2-castavall-corner-guild-treck.jpg','map' => 'Bloodtide Coast','way_point' => 'Castavall Waypoint','cnname' => '','code' => '[&BK4BAAA=]'),
array('name' => 'Cathedral\'s Cavity','pic_url' => 'gw2-cathedrals-cavity-guild-treck.jpg','map' => 'Malchor\'s Leap','way_point' => 'Wren Waypoint','cnname' => '','code' => '[&BKwCAAA=]'),
array('name' => 'Cave Bear Cache','pic_url' => 'gw2-cave-bear-cache-guild-treck.jpg','map' => 'Snowden Drifts','way_point' => 'Snowhawk Landing Waypoint','cnname' => '','code' => '[&BL8AAAA=]'),
array('name' => 'Cave Spider Nidus','pic_url' => 'gw2-cave-spider-nidus-guild-treck.jpg','map' => 'Lornar\'s Pass','way_point' => 'Pinnacle Enclave Waypoint','cnname' => '','code' => '[&BJgBAAA=]'),
array('name' => 'Claypool Bailey','pic_url' => 'gw2-claypool-bailey-guild-treck.jpg','map' => 'Queensdale','way_point' => 'Claypool Waypoint','cnname' => '','code' => '[&BPYAAAA=]'),
array('name' => 'Constellation Parapet','pic_url' => 'gw2-constellation-parapet-guild-treck.jpg','map' => 'The Grove','way_point' => 'Reckoner\'s Waypoint','cnname' => '','code' => '[&BLsEAAA=]'),
array('name' => 'Corruption\'s Teeth','pic_url' => 'gw2-corruptions-teeth-guild-treck.jpg','map' => 'Frostgorge Sound','way_point' => 'Drakkar Waypoint','cnname' => '','code' => '[&BIYCAAA=]'),
array('name' => 'Covington\'s Stowage','pic_url' => 'gw2-covingtons-stowage-guild-treck.jpg','map' => 'Bloodtide Coast','way_point' => 'Lauging Gull Waypoint','cnname' => '','code' => '[&BKgBAAA=]'),
array('name' => 'Cutthroat\'s Rest','pic_url' => 'gw2-cutthroats-rest-guild-treck.jpg','map' => 'Gendarran Fields','way_point' => 'Brigantine Waypoint','cnname' => '','code' => '[&BM0DAAA=]'),
array('name' => 'Cymbel\'s Glen','pic_url' => 'gw2-cymbels-glen-guild-treck.jpg','map' => 'Fields of Ruin','way_point' => 'Deathblade\'s Watch Waypoint','cnname' => '','code' => '[&BNQAAAA=]'),
array('name' => 'Dawngleam Pergola','pic_url' => 'gw2-dawngleam-pergola-guild-treck.jpg','map' => 'The Grove','way_point' => 'Ronan\'s Waypoint','cnname' => '','code' => '[&BLwEAAA=]'),
array('name' => 'Deepmire Diver','pic_url' => 'gw2-deepmire-diver-guild-treck.jpg','map' => 'Mount Maelstrom','way_point' => 'Oxbow Isle Waypoint','cnname' => '','code' => '[&BNECAAA=]'),
array('name' => 'Defiled Delve','pic_url' => 'gw2-defiled-delve-guild-treck.jpg','map' => 'Kessex Hills','way_point' => 'Darkwound Waypoint','cnname' => '','code' => '[&BBEAAAA=]'),
array('name' => 'Delight\'s Balcony','pic_url' => 'gw2-delights-balcony-guild-treck.jpg','map' => 'Malchor\'s Leap','way_point' => 'Pagga\'s Waypoint','cnname' => '','code' => '[&BKYCAAA=]'),
array('name' => 'Destiny\'s Guildhall','pic_url' => 'gw2-destinys-guildhall-guild-treck.jpg','map' => 'Queensdale','way_point' => 'Shaemoor Waypoint','cnname' => '','code' => '[&BO8AAAA=]'),
array('name' => 'Dirtclaw Cleft','pic_url' => 'gw2-dirtclaw-cleft-guild-treck.jpg','map' => 'Iron Marches','way_point' => 'Bloodfin Lake Waypoint','cnname' => '','code' => '[&BOMBAAA=]'),
array('name' => 'Doefalls Court','pic_url' => 'gw2-doefalls-court-guild-treck.jpg','map' => 'Plains of Ashford','way_point' => 'Ascalon City Waypoint','cnname' => '','code' => '[&BIcBAAA=]'),
array('name' => 'Drakecleft Shelf','pic_url' => 'gw2-drakecleft-shelf-guild-treck.jpg','map' => 'Fields of Ruin','way_point' => 'Fangfury Watch Waypoint','cnname' => '','code' => '[&BEwBAAA=]'),
array('name' => 'Drakehatch Shore','pic_url' => 'gw2-drakehatch-shore-guild-treck.jpg','map' => 'Diessa Plateau','way_point' => 'Breachwater Waypoint','cnname' => '','code' => '[&BGQBAAA=]'),
array('name' => 'Droknah\'s Gate','pic_url' => 'gw2-droknahs-gate-guild-treck.jpg','map' => 'Mount Maelstrom','way_point' => 'Old Sledge Site Waypoint','cnname' => '','code' => '[&BNQCAAA=]'),
array('name' => 'Drowned Plaza','pic_url' => 'gw2-drowned-plaza-guild-treck.jpg','map' => 'Straits of Devastation','way_point' => 'Royal Forum Waypoint','cnname' => '','code' => '[&BPMCAAA=]'),
array('name' => 'Dwayna’s Fount','pic_url' => 'gw2-dwaynas-fount-guild-treck.jpg','map' => 'Divinity\'s Reach','way_point' => 'Commons Waypoint','cnname' => '','code' => '[&BCoDAAA=]'),
array('name' => 'East End Falls','pic_url' => 'gw2-east-end-falls-guild-treck.jpg','map' => 'Brisban Wildlands','way_point' => 'East End Waypoint','cnname' => '','code' => '[&BGAAAAA=]'),
array('name' => 'East Lurk Alley','pic_url' => 'gw2-east-lurk-alley-guild-treck.jpg','map' => 'Divinity\'s Reach','way_point' => 'Dwayna Waypoint','cnname' => '','code' => '[&BCMDAAA=]'),
array('name' => 'Elise\'s Surprise','pic_url' => 'gw2-elises-surprise-guild-treck.jpg','map' => 'Harathi Hinterlands','way_point' => 'Demetra Waypoint','cnname' => '','code' => '[&BKsAAAA=]'),
array('name' => 'Ettinbreath Lair','pic_url' => 'gw2-ettinbreath-lair-guild-treck.jpg','map' => 'Lornar\'s Pass','way_point' => 'Demon\'s Maw Waypoint','cnname' => '','code' => '[&BOYAAAA=]'),
array('name' => 'Fathom Five Forcefield','pic_url' => 'gw2-fathom-five-forcefield-guild-treck.jpg','map' => 'Straits of Devastation','way_point' => 'Vesper Bell Waypoint','cnname' => '','code' => '[&BPICAAA=]'),
array('name' => 'Fawcett\'s Porch','pic_url' => 'gw2-fawcetts-porch-guild-treck.jpg','map' => 'Harathi Hinterlands','way_point' => 'Arcallion Waypoint','cnname' => '','code' => '[&BMMAAAA=]'),
array('name' => 'Fire Imp Pocket','pic_url' => 'gw2-fire-imp-pocket-guild-treck.jpg','map' => 'Mount Maelstrom','way_point' => 'Maelstrom\'s Waypoint','cnname' => '','code' => '[&BM0CAAA=]'),
array('name' => 'Firefrog Springs','pic_url' => 'gw2-firefrog-springs-guild-treck.jpg','map' => 'Sparkfly Fen','way_point' => 'Flamefrog Waypoint','cnname' => '','code' => '[&BMwBAAA=]'),
array('name' => 'Firewatch Flybridge','pic_url' => 'gw2-firewatch-flybridge-guild-treck.jpg','map' => 'Iron Marches','way_point' => 'Firewatch Encampment Waypoint','cnname' => '','code' => '[&BO0BAAA=]'),
array('name' => 'Fisher\'s Crag','pic_url' => 'gw2-fishers-crag-guild-treck.jpg','map' => 'Metrica Province','way_point' => 'Old Golem Factory Waypoint','cnname' => '','code' => '[&BK4EAAA=]'),
array('name' => 'Flakk\'s Lapidary Nook','pic_url' => 'gw2-flakks-lapidary-nook-guild-treck.jpg','map' => 'Rata Sum','way_point' => 'Accountancy Waypoint','cnname' => '','code' => '[&BLYEAAA=]'),
array('name' => 'Forager\'s Midden','pic_url' => 'gw2-foragers-midden-guild-treck.jpg','map' => 'Dredgehaunt Cliffs','way_point' => 'Steelbrachen Waypoint','cnname' => '','code' => '[&BFsCAAA=]'),
array('name' => 'Forbidden Shear','pic_url' => 'gw2-forbidden-shear-guild-treck.jpg','map' => 'Malchor\'s Leap','way_point' => 'Murmur Waypoint','cnname' => '','code' => '[&BK8CAAA=]'),
array('name' => 'Foreman\'s Recess','pic_url' => 'gw2-foremans-recess-guild-treck.jpg','map' => 'Dredgehaunt Cliffs','way_point' => 'Dociu Waypoint','cnname' => '','code' => '[&BFgCAAA=]'),
array('name' => 'Forgotten Grotto','pic_url' => 'gw2-forgotten-grotto-guild-treck.jpg','map' => 'Blazeridge Steppes','way_point' => 'Terra Carorunda Waypoint','cnname' => '','code' => '[&BAECAAA=]'),
array('name' => 'Founder\'s Flagon Hearth','pic_url' => 'gw2-founders-flagon-hearth-guild-treck.jpg','map' => 'Fields of Ruin','way_point' => 'Kestrel Waypoint','cnname' => '','code' => '[&BD0EAAA=]'),
array('name' => 'Freestand Scaffold','pic_url' => 'gw2-freestand-scaffold-guild-treck.jpg','map' => 'Black Citadel','way_point' => 'Ruins of Rin Waypoint','cnname' => '','code' => '[&BKwDAAA=]'),
array('name' => 'Frozen Antrum','pic_url' => 'gw2-frozen-antrum-guild-treck.jpg','map' => 'Timberline Falls','way_point' => 'White Paper Waypoint','cnname' => '','code' => '[&BE8CAAA=]'),
array('name' => 'Gallow Canyons','pic_url' => 'gw2-gallow-canyons-guild-treck.jpg','map' => 'Brisban Wildlands','way_point' => 'Gallowfields Waypoint','cnname' => '','code' => '[&BGMAAAA=]'),
array('name' => 'Gardenroot Alcove','pic_url' => 'gw2-gardenroot-alcove-guild-treck.jpg','map' => 'The Grove','way_point' => 'Reckoner\'s Waypoint','cnname' => '','code' => '[&BLsEAAA=]'),
array('name' => 'Gnashar\'s Viewpoint','pic_url' => 'gw2-gnashars-viewpoint-guild-treck.jpg','map' => 'Brisban Wildlands','way_point' => 'Wendon Waypoint','cnname' => '','code' => '[&BF0AAAA=]'),
array('name' => 'Green Moa Paddock','pic_url' => 'gw2-green-moa-paddock-guild-treck.jpg','map' => 'Caledon Forest','way_point' => 'Caledon Haven Waypoint','cnname' => '','code' => '[&BDwBAAA=]'),
array('name' => 'Grenth\'s Pavillion','pic_url' => 'gw2-grenths-pavillion-guild-treck.jpg','map' => 'Divinity\'s Reach','way_point' => 'Grenth Waypoint','cnname' => '','code' => '[&BCQDAAA=]'),
array('name' => 'Grimdottir\'s Duty','pic_url' => 'gw2-grimdottirs-duty-guild-treck.jpg','map' => 'Hoelbrak','way_point' => 'Shelter Rock Waypoint','cnname' => '','code' => '[&BIsDAAA=]'),
array('name' => 'Guardian Overwatch','pic_url' => 'gw2-guardian-overwatch-guild-treck.jpg','map' => 'Harathi Hinterlands','way_point' => 'Barricade Camp Waypoint','cnname' => '','code' => '[&BK0AAAA=]'),
array('name' => 'Hawkeye Perch','pic_url' => 'gw2-hawkeye-perch-guild-treck.jpg','map' => 'Timberline Falls','way_point' => 'Serpent Waypoint','cnname' => '','code' => '[&BEUCAAA=]'),
array('name' => 'Heart Speaks Notch','pic_url' => 'gw2-heart-speaks-notch-guild-treck.jpg','map' => 'Fireheart Rise','way_point' => 'Apostate Waypoint','cnname' => '','code' => '[&BB0CAAA=]'),
array('name' => 'Heartwood Honey Cache','pic_url' => 'gw2-heartwood-honey-cache-guild-treck.jpg','map' => 'Queensdale','way_point' => 'Phinney Waypoint','cnname' => '','code' => '[&BPMAAAA=]'),
array('name' => 'Heidi’s Showpiece','pic_url' => 'gw2-heidis-showpiece-guild-treck.jpg','map' => 'Harathi Hinterlands','way_point' => 'Seraph\'s Landing Waypoint','cnname' => '','code' => '[&BKcAAAA=]'),
array('name' => 'Hermit\'s Roost','pic_url' => 'gw2-hermits-roost-guild-treck.jpg','map' => 'Fields of Ruin','way_point' => 'Rosko\'s Campsite Waypoint','cnname' => '','code' => '[&BNgAAAA=]'),
array('name' => 'Hidden Owl Distillery','pic_url' => 'gw2-hidden-owl-distillery-guild-treck.jpg','map' => 'Snowden Drifts','way_point' => 'Owl Waypoint','cnname' => '','code' => '[&BMEAAAA=]'),
array('name' => 'Holystone Sanctum','pic_url' => 'gw2-holystone-sanctum-guild-treck.jpg','map' => 'Diessa Plateau','way_point' => 'Sanctum Waypoint','cnname' => '','code' => '[&BMUDAAA=]'),
array('name' => 'Icewurm Trench','pic_url' => 'gw2-icewurm-trench-guild-treck.jpg','map' => 'Frostgorge Sound','way_point' => 'Dimotiki Waypoint','cnname' => '','code' => '[&BH8CAAA=]'),
array('name' => 'Ideation Leap','pic_url' => 'gw2-ideation-leap-guild-treck.jpg','map' => 'Rata Sum','way_point' => 'Incubation Waypoint','cnname' => '','code' => '[&BLUEAAA=]'),
array('name' => 'Imphaunt Hallow','pic_url' => 'gw2-imphaunt-hallow-guild-treck.jpg','map' => 'Caledon Forest','way_point' => 'Wychmire Waypoint','cnname' => '','code' => '[&BEEBAAA=]'),
array('name' => 'Irondock Viewpoint','pic_url' => 'gw2-irondock-viewpoint-guild-treck.jpg','map' => 'Plains of Ashford','way_point' => 'Duskrend Overlook Waypoint','cnname' => '','code' => '[&BIkBAAA=]'),
array('name' => 'Isenfell Wash','pic_url' => 'gw2-isenfell-wash-guild-treck.jpg','map' => 'Snowden Drifts','way_point' => 'Isenfall Waypoint','cnname' => '','code' => '[&BLgAAAA=]'),
array('name' => 'Isgarren Viewpoint','pic_url' => 'gw2-isgarren-viewpoint-guild-treck.jpg','map' => 'Kessex Hills','way_point' => 'Darkwound Waypoint','cnname' => '','code' => '[&BBEAAAA=]'),
array('name' => 'Jaguar Pride Den','pic_url' => 'gw2-jaguar-pride-den-guild-treck.jpg','map' => 'Metrica Province','way_point' => 'Muridian Waypoint','cnname' => '','code' => '[&BEcAAAA=]'),
array('name' => 'Junker\'s Apex','pic_url' => 'gw2-junkers-apex-guild-treck.jpg','map' => 'Black Citadel','way_point' => 'Junker\'s Waypoint','cnname' => '','code' => '[&BDcEAAA=]'),
array('name' => 'Kaldar’s Hot Seat','pic_url' => 'gw2-kaldars-hot-seat-guild-treck.jpg','map' => 'Hoelbrak','way_point' => 'Eastern Watchpost Waypoint','cnname' => '','code' => '[&BI0DAAA=]'),
array('name' => 'Kari\'s Hot Spot','pic_url' => 'gw2-karis-hot-spot-guild-treck.jpg','map' => 'Kessex Hills','way_point' => 'Cereboth Waypoint','cnname' => '','code' => '[&BBIAAAA=]'),
array('name' => 'Kegbrawl Watch','pic_url' => 'gw2-kegbrawl-watch-guild-treck.jpg','map' => 'Hoelbrak','way_point' => 'Hero\'s Compass Waypoint','cnname' => '','code' => '[&BJADAAA=]'),
array('name' => 'Kevach’s Strongroom','pic_url' => 'gw2-kevachs-strongroom-guild-treck.jpg','map' => 'Wayfarer Foothills','way_point' => 'Lostvyrm Cave Waypoint','cnname' => '','code' => '[&BMEDAAA=]'),
array('name' => 'Lakebottom Underpass','pic_url' => 'gw2-lakebottom-underpass-guild-treck.jpg','map' => 'Queensdale','way_point' => 'Ojon\'s Lumbermill Waypoint','cnname' => '','code' => '[&BPkAAAA=]'),
array('name' => 'Lawen Grotto','pic_url' => 'gw2-lawen-grotto-guild-treck.jpg','map' => 'Gendarran Fields','way_point' => 'First Haven Waypoint','cnname' => '','code' => '[&BIsBAAA=]'),
array('name' => 'Lightfoot Dock','pic_url' => 'gw2-lightfoot-dock-guild-treck.jpg','map' => 'Straits of Devastation','way_point' => 'Thunderhead Waypoint','cnname' => '','code' => '[&BPACAAA=]'),
array('name' => 'Lily\'s Bivvy','pic_url' => 'gw2-lilys-bivvy-guild-treck.jpg','map' => 'Fireheart Rise','way_point' => 'Icespear\'s Waypoint','cnname' => '','code' => '[&BCACAAA=]'),
array('name' => 'Lionguard Larder','pic_url' => 'gw2-lionguard-larder-guild-treck.jpg','map' => 'Wayfarer Foothills','way_point' => 'Twinspur Haven Waypoint','cnname' => '','code' => '[&BH0BAAA=]'),
array('name' => 'Lychcroft Wardenship','pic_url' => 'gw2-lychcroft-wardenship-guild-treck.jpg','map' => 'Kessex Hills','way_point' => 'Shadowheart Site Waypoint','cnname' => '','code' => '[&BAwAAAA=]'),
array('name' => 'Magihedron Corner','pic_url' => 'gw2-magihedron-corner-guild-treck.jpg','map' => 'Rata Sum','way_point' => 'Metrical Court Waypoint','cnname' => '','code' => '[&BBMEAAA=]'),
array('name' => 'Master Control LIN39','pic_url' => 'gw2-master-control-lin39-guild-treck.jpg','map' => 'Metrica Province','way_point' => 'Muridian Waypoint','cnname' => '','code' => '[&BEcAAAA=]'),
array('name' => 'Meltwater Cave','pic_url' => 'gw2-meltwater-cave-guild-treck.jpg','map' => 'Timberline Falls','way_point' => 'Scale Strand Waypoint','cnname' => '','code' => '[&BEgCAAA=]'),
array('name' => 'Mina\'s Target Shoot','pic_url' => 'gw2-minas-target-shoot-guild-treck.jpg','map' => 'Divinity\'s Reach','way_point' => 'Commons Waypoint','cnname' => '','code' => '[&BCoDAAA=]'),
array('name' => 'Mistriven Shelf','pic_url' => 'gw2-mistriven-shelf-guild-treck.jpg','map' => 'Lornar\'s Pass','way_point' => 'Mistriven Waypoint','cnname' => '','code' => '[&BJkBAAA=]'),
array('name' => 'Moleberia Prison','pic_url' => 'gw2-moleberia-prison-guild-treck.jpg','map' => 'Wayfarer Foothills','way_point' => 'Halvaunt Waypoint','cnname' => '','code' => '[&BHgBAAA=]'),
array('name' => 'Monument to the Ancient One','pic_url' => 'gw2-monument-to-the-ancient-one-guild-treck.jpg','map' => 'Southsun Cove','way_point' => 'Owain\'s Refuge Waypoint','cnname' => '','code' => '[&BNgGAAA=]'),
array('name' => 'Narrowkraal Crossing','pic_url' => 'gw2-narrowkraal-crossing-guild-treck.jpg','map' => 'Fields of Ruin','way_point' => 'Ogre Road Waypoint','cnname' => '','code' => '[&BE8BAAA=]'),
array('name' => 'Necrolith Landing','pic_url' => 'gw2-necrolith-landing-guild-treck.jpg','map' => 'The Grove','way_point' => 'Caledon Waypoint','cnname' => '','code' => '[&BBIEAAA=]'),
array('name' => 'Orecart Hoist','pic_url' => 'gw2-orecart-hoist-guild-treck.jpg','map' => 'Fireheart Rise','way_point' => 'Pig Iron Waypoint','cnname' => '','code' => '[&BBcCAAA=]'),
array('name' => 'Orvanic Sourcewaters','pic_url' => 'gw2-orvanic-sourcewaters-guild-treck.jpg','map' => 'Sparkfly Fen','way_point' => 'Ocean\'s Gullet Waypoint','cnname' => '','code' => '[&BMkBAAA=]'),
array('name' => 'Osenfold Counterweights','pic_url' => 'gw2-osenfold-counterweights-guild-treck.jpg','map' => 'Wayfarer Foothills','way_point' => 'Osenfold Waypoint','cnname' => '','code' => '[&BAEEAAA=]'),
array('name' => 'Overlord Lodge','pic_url' => 'gw2-overlord-lodge-guild-treck.jpg','map' => 'Kessex Hills','way_point' => 'Overlord\'s Waypoint','cnname' => '','code' => '[&BAQAAAA=]'),
array('name' => 'Phasmatis Prospect','pic_url' => 'gw2-phasmatis-prospect-guild-treck.jpg','map' => 'Plains of Ashford','way_point' => 'Irondock Shipyard Waypoint','cnname' => '','code' => '[&BIoBAAA=]'),
array('name' => 'Pochtecatl’s Desire','pic_url' => 'gw2-pochtecatls-desire-guild-treck.jpg','map' => 'Bloodtide Coast','way_point' => 'Jelako Waypoint','cnname' => '','code' => '[&BK8BAAA=]'),
array('name' => 'Port Authority Lost and Found','pic_url' => 'gw2-port-authority-lost-and-found-guild-treck.jpg','map' => 'Rata Sum','way_point' => 'Port Waypoint','cnname' => '','code' => '[&BAcFAAA=]'),
array('name' => 'Portmatt\'s Promontory','pic_url' => 'gw2-portmatts-promontory-guild-treck.jpg','map' => 'Bloodtide Coast','way_point' => 'Sorrowful Waypoint','cnname' => '','code' => '[&BKQBAAA=]'),
array('name' => 'Provatum Carcer','pic_url' => 'gw2-provatum-carcer-guild-treck.jpg','map' => 'Fireheart Rise','way_point' => 'Keeper\'s Waypoint','cnname' => '','code' => '[&BCYCAAA=]'),
array('name' => 'Ramview Peak','pic_url' => 'gw2-ramview-peak-guild-treck.jpg','map' => 'Dredgehaunt Cliffs','way_point' => 'Travelen\'s Waypoint','cnname' => '','code' => '[&BGQCAAA=]'),
array('name' => 'Raptor\'s Aerie','pic_url' => 'gw2-raptors-aerie-guild-treck.jpg','map' => 'Iron Marches','way_point' => 'Town of Cowlfang\'s Star Waypoint','cnname' => '','code' => '[&BOsBAAA=]'),
array('name' => 'Raptor\'s Perch','pic_url' => 'gw2-raptors-perch-guild-treck.jpg','map' => 'Gendarran Fields','way_point' => 'Winter Haven Waypoint','cnname' => '','code' => '[&BO4AAAA=]'),
array('name' => 'Rata Pten Portico','pic_url' => 'gw2-rata-pten-portico-guild-treck.jpg','map' => 'Mount Maelstrom','way_point' => 'Criterion Waypoint','cnname' => '','code' => '[&BMkCAAA=]'),
array('name' => 'Raven Nook','pic_url' => 'gw2-raven-nook-guild-treck.jpg','map' => 'Hoelbrak','way_point' => 'Raven Waypoint','cnname' => '','code' => '[&BIgDAAA=]'),
array('name' => 'Reef Drake Den','pic_url' => 'gw2-reef-drake-den-guild-treck.jpg','map' => 'Southsun Cove','way_point' => 'Pearl Islet Waypoint','cnname' => '','code' => '[&BNUGAAA=]'),
array('name' => 'Restless Footings','pic_url' => 'gw2-restless-footings-guild-treck.jpg','map' => 'Mount Maelstrom','way_point' => 'Irwin Isle Waypoint','cnname' => '','code' => '[&BNICAAA=]'),
array('name' => 'Reverberant\'s Watch','pic_url' => 'gw2-reverberants-watch-guild-treck.jpg','map' => 'Wayfarer Foothills','way_point' => 'Darkriven Waypoint','cnname' => '','code' => '[&BHUBAAA=]'),
array('name' => 'Risewild Green','pic_url' => 'gw2-risewild-green-guild-treck.jpg','map' => 'Bloodtide Coast','way_point' => 'Remanda Waypoint','cnname' => '','code' => '[&BKcBAAA=]'),
array('name' => 'Rurik\'s View','pic_url' => 'gw2-ruriks-view-guild-treck.jpg','map' => 'Divinity\'s Reach','way_point' => 'Rurikton Waypoint','cnname' => '','code' => '[&BCsDAAA=]'),
array('name' => 'Saltflood Altar','pic_url' => 'gw2-saltflood-altar-guild-treck.jpg','map' => 'Sparkfly Fen','way_point' => 'Saltflood Waypoint','cnname' => '','code' => '[&BMcBAAA=]'),
array('name' => 'Sandwurm Prowl','pic_url' => 'gw2-sandwurm-prowl-guild-treck.jpg','map' => 'Southsun Cove','way_point' => 'Pearl Islet Waypoint','cnname' => '','code' => '[&BNUGAAA=]'),
array('name' => 'Scholar\'s Blind','pic_url' => 'gw2-scholars-blind-guild-treck.jpg','map' => 'Dredgehaunt Cliffs','way_point' => 'Steelbrachen Waypoint','cnname' => '','code' => '[&BFsCAAA=]'),
array('name' => 'Scourgejaw Watchtower','pic_url' => 'gw2-scourgejaw-watchtower-guild-treck.jpg','map' => 'Iron Marches','way_point' => 'Sleekfur Encampment Waypoint','cnname' => '','code' => '[&BOgBAAA=]'),
array('name' => 'Scriptorium Nook','pic_url' => 'gw2-scriptorium-nook-guild-treck.jpg','map' => 'Black Citadel','way_point' => 'Factorium Waypoint','cnname' => '','code' => '[&BKcDAAA=]'),
array('name' => 'Sea Scorpion\'s Eye','pic_url' => 'gw2-sea-scorpions-eye-guild-treck.jpg','map' => 'Cursed Shore','way_point' => 'Meddler\'s Waypoint','cnname' => '','code' => '[&BB4DAAA=]'),
array('name' => 'Sentinel Sink','pic_url' => 'gw2-sentinel-sink-guild-treck.jpg','map' => 'Iron Marches','way_point' => 'Brandwatch Encampment Waypoint','cnname' => '','code' => '[&BOkBAAA=]'),
array('name' => 'Sepulchre Skylight','pic_url' => 'gw2-sepulchre-skylight-guild-treck.jpg','map' => 'Straits of Devastation','way_point' => 'Rally Waypoint','cnname' => '','code' => '[&BNIEAAA=]'),
array('name' => 'Sharkhollow\'s Edge','pic_url' => 'gw2-sharkhollows-edge-guild-treck.jpg','map' => 'Blazeridge Steppes','way_point' => 'Spintercrest Fort Waypoint','cnname' => '','code' => '[&BFEDAAA=]'),
array('name' => 'Shattered Loft','pic_url' => 'gw2-shattered-loft-guild-treck.jpg','map' => 'Sparkfly Fen','way_point' => 'Fort Cadence Waypoint','cnname' => '','code' => '[&BMUBAAA=]'),
array('name' => 'Siamoth Refuge','pic_url' => 'gw2-siamoth-refuge-guild-treck.jpg','map' => 'Sparkfly Fen','way_point' => 'Brackwater Waypoint','cnname' => '','code' => '[&BM4BAAA=]'),
array('name' => 'Skalecatch Butcher Shop','pic_url' => 'gw2-skalecatch-butcher-shop-guild-treck.jpg','map' => 'Iron Marches','way_point' => 'Village of Scalecatch Waypoint','cnname' => '','code' => '[&BOcBAAA=]'),
array('name' => 'Skalefound Cove','pic_url' => 'gw2-skalefound-cove-guild-treck.jpg','map' => 'Fireheart Rise','way_point' => 'Tuyere Command Post Waypoint','cnname' => '','code' => '[&BBgCAAA=]'),
array('name' => 'Skalesplash Falls','pic_url' => 'gw2-skalesplash-falls-guild-treck.jpg','map' => 'Timberline Falls','way_point' => 'Okarinoo Waypoint','cnname' => '','code' => '[&BEYCAAA=]'),
array('name' => 'Skalestash Hideaway','pic_url' => 'gw2-skalestash-hideaway-guild-treck.jpg','map' => 'Plains of Ashford','way_point' => 'Feritas Waypoint','cnname' => '','code' => '[&BJcDAAA=]'),
array('name' => 'Skelknest Borehole','pic_url' => 'gw2-skelknest-borehole-guild-treck.jpg','map' => 'Frostgorge Sound','way_point' => 'Slough of Despond Waypoint','cnname' => '','code' => '[&BHwCAAA=]'),
array('name' => 'Skibo Hall Dormitory','pic_url' => 'gw2-skibo-hall-dormitory-guild-treck.jpg','map' => 'Rata Sum','way_point' => 'Auxiliary Waypoint','cnname' => '','code' => '[&BLkEAAA=]'),
array('name' => 'Skyshrine Scratch','pic_url' => 'gw2-skyshrine-scratch-guild-treck.jpg','map' => 'Harathi Hinterlands','way_point' => 'Grey Gritta\'s Waypoint','cnname' => '','code' => '[&BKkAAAA=]'),
array('name' => 'Snowden Safehouse','pic_url' => 'gw2-snowden-safehouse-guild-treck.jpg','map' => 'Snowden Drifts','way_point' => 'Highpass Haven Waypoint','cnname' => '','code' => '[&BLUAAAA=]'),
array('name' => 'Snowhowl Den','pic_url' => 'gw2-snowhowl-den-guild-treck.jpg','map' => 'Snowden Drifts','way_point' => 'Snowhawk Landing Waypoint','cnname' => '','code' => '[&BL8AAAA=]'),
array('name' => 'Soggorsort Rotunda','pic_url' => 'gw2-soggorsort-rotunda-guild-treck.jpg','map' => 'Caledon Forest','way_point' => 'Hamlet of Annwen Waypoint','cnname' => '','code' => '[&BD8BAAA=]'),
array('name' => 'Soren Draa Rest Stop','pic_url' => 'gw2-soren-draa-rest-stop-guild-treck.jpg','map' => 'Metrica Province','way_point' => 'Soren Draa Waypoint','cnname' => '','code' => '[&BEAAAAA=]'),
array('name' => 'Source of Lament','pic_url' => 'gw2-source-of-lament-guild-treck.jpg','map' => 'Frostgorge Sound','way_point' => 'Skyheight Steading Waypoint','cnname' => '','code' => '[&BIECAAA=]'),
array('name' => 'Sparwind\'s Lounge','pic_url' => 'gw2-sparwinds-lounge-guild-treck.jpg','map' => 'Black Citadel','way_point' => 'Imperator\'s Waypoint','cnname' => '','code' => '[&BK0DAAA=]'),
array('name' => 'Spectrehaunt Socket','pic_url' => 'gw2-spectrehaunt-socket-guild-treck.jpg','map' => 'Malchor\'s Leap','way_point' => 'Lights Waypoint','cnname' => '','code' => '[&BLICAAA=]'),
array('name' => 'Steamscrap Overlook','pic_url' => 'gw2-steamscrap-overlook-guild-treck.jpg','map' => 'Lornar\'s Pass','way_point' => 'Lamentation Waypoint','cnname' => '','code' => '[&BOoAAAA=]'),
array('name' => 'Steampipe Perch','pic_url' => 'gw2-steampipe-perch-guild-treck.jpg','map' => 'Southsun Cove','way_point' => 'Kiel\'s Outpost Waypoint','cnname' => '','code' => '[&BNwGAAA=]'),
array('name' => 'Steamy Steps','pic_url' => 'gw2-steamy-steps-guild-treck.jpg','map' => 'Southsun Cove','way_point' => 'Point Lion Waypoint','cnname' => '','code' => '[&BNwGAAA=]'),
array('name' => 'Steelband\'s Tunnel','pic_url' => 'gw2-steelbands-tunnel-guild-treck.jpg','map' => 'Blazeridge Steppes','way_point' => 'Tumok\'s Waypoint','cnname' => '','code' => '[&BPsBAAA=]'),
array('name' => 'Stentor Shelter','pic_url' => 'gw2-stentor-shelter-guild-treck.jpg','map' => 'Straits of Devastation','way_point' => 'Signal Peak Waypoint','cnname' => '','code' => '[&BO0CAAA=]'),
array('name' => 'Stonebore Spiderhole','pic_url' => 'gw2-stonebore-spiderhole-guild-treck.jpg','map' => 'Gendarran Fields','way_point' => 'Talajian Waypoint','cnname' => '','code' => '[&BIwBAAA=]'),
array('name' => 'Strongpaw\'s Garden','pic_url' => 'gw2-strongpaws-garden-guild-treck.jpg','map' => 'Diessa Plateau','way_point' => 'Nageling Waypoint','cnname' => '','code' => '[&BN0AAAA=]'),
array('name' => 'Tactical Retreat','pic_url' => 'gw2-tactical-retreat-guild-treck.jpg','map' => 'Cursed Shore','way_point' => 'Shipwreck Rock Waypoint','cnname' => '','code' => '[&BOQGAAA=]'),
array('name' => 'Tagotl Shore','pic_url' => 'gw2-tagotl-shore-guild-treck.jpg','map' => 'Kessex Hills','way_point' => 'Viathan Waypoint','cnname' => '','code' => '[&BBAAAAA=]'),
array('name' => 'Talus Steps','pic_url' => 'gw2-talus-steps-guild-treck.jpg','map' => 'Timberline Falls','way_point' => 'Talus Waypoint','cnname' => '','code' => '[&BEQCAAA=]'),
array('name' => 'Tarstar Copse','pic_url' => 'gw2-tarstar-copse-guild-treck.jpg','map' => 'Fireheart Rise','way_point' => 'Apostate Waypoint','cnname' => '','code' => '[&BB0CAAA=]'),
array('name' => 'Tekki’s Drawing Board','pic_url' => 'gw2-tekkis-drawing-board-guild-treck.jpg','map' => 'Brisban Wildlands','way_point' => 'Ulta Metamagicals Waypoint','cnname' => '','code' => '[&BGUAAAA=]'),
array('name' => 'Thaumanova Spillway','pic_url' => 'gw2-thaumanova-spillway-guild-treck.jpg','map' => 'Metrica Province','way_point' => 'Muridian Waypoint','cnname' => '','code' => '[&BEcAAAA=]'),
array('name' => 'The Karka Club','pic_url' => 'gw2-the-karka-club-guild-treck.jpg','map' => 'Southsun Cove','way_point' => 'Pearl Islet Waypoint','cnname' => '','code' => '[&BNUGAAA=]'),
array('name' => 'The People\'s Deadlock','pic_url' => 'gw2-the-peoples-deadlock-guild-treck.jpg','map' => 'Frostgorge Sound','way_point' => 'Groznev Waypoint','cnname' => '','code' => '[&BHkCAAA=]'),
array('name' => 'The Workers\' Stores','pic_url' => 'gw2-the-workers-stores-guild-treck.jpg','map' => 'Dredgehaunt Cliffs','way_point' => 'Grey Road Waypoint','cnname' => '','code' => '[&BFoCAAA=]'),
array('name' => 'Toxal Spill','pic_url' => 'gw2-toxal-spill-guild-treck.jpg','map' => 'Brisban Wildlands','way_point' => 'Mirkrise Waypoint','cnname' => '','code' => '[&BHYAAAA=]'),
array('name' => 'Tower of Tribulation','pic_url' => 'gw2-tower-of-tribulation-guild-treck.jpg','map' => 'Dredgehaunt Cliffs','way_point' => 'Tribulation Waypoint','cnname' => '','code' => '[&BFYCAAA=]'),
array('name' => 'Trader\'s Stash','pic_url' => 'gw2-traders-stash-guild-treck.jpg','map' => 'Hoelbrak','way_point' => 'Peeta\'s Waypoint','cnname' => '','code' => '[&BI8DAAA=]'),
array('name' => 'Trolltrap Pit','pic_url' => 'gw2-trolltrap-pit-guild-treck.jpg','map' => 'Lornar\'s Pass','way_point' => 'Durmand Priory Waypoint','cnname' => '','code' => '[&BOkAAAA=]'),
array('name' => 'Turai Tavern Stillroom','pic_url' => 'gw2-turai-tavern-stillroom-guild-treck.jpg','map' => 'Divinity\'s Reach','way_point' => 'Balthazar Waypoint','cnname' => '','code' => '[&BCgDAAA=]'),
array('name' => 'Ulta Scraproom','pic_url' => 'gw2-ulta-scraproom-guild-treck.jpg','map' => 'Brisban Wildlands','way_point' => 'Ulta Metamagicals Waypoint','cnname' => '','code' => '[&BGUAAAA=]'),
array('name' => 'Unseen Scratch','pic_url' => 'gw2-unseen-scratch-guild-treck.jpg','map' => 'Caledon Forest','way_point' => 'Caledon Haven Waypoint','cnname' => '','code' => '[&BDwBAAA=]'),
array('name' => 'Upsilon Hyperboloid','pic_url' => 'gw2-upsilon-hyperboloid-guild-treck.jpg','map' => 'Malchor\'s Leap','way_point' => 'Waste Hollows Waypoint','cnname' => '','code' => '[&BKgCAAA=]'),
array('name' => 'Usharr’s Threshold','pic_url' => 'gw2-usharrs-threshold-guild-treck.jpg','map' => 'Sparkfly Fen','way_point' => 'Toade\'s Head Waypoint','cnname' => '','code' => '[&BMsBAAA=]'),
array('name' => 'Vacant Hermitage','pic_url' => 'gw2-vacant-hermitage-guild-treck.jpg','map' => 'Blazeridge Steppes','way_point' => 'Guardian Stone Waypoint','cnname' => '','code' => '[&BP8BAAA=]'),
array('name' => 'Venison Hollow','pic_url' => 'gw2-venison-hollow-guild-treck.jpg','map' => 'Lornar\'s Pass','way_point' => 'Vanjir\'s Stead Waypoint','cnname' => '','code' => '[&BOUAAAA=]'),
array('name' => 'Verdance Font','pic_url' => 'gw2-verdance-font-guild-treck.jpg','map' => 'Cursed Shore','way_point' => 'Verdance Waypoint','cnname' => '','code' => '[&BBsDAAA=]'),
array('name' => 'Vizier\'s Anteport','pic_url' => 'gw2-viziers-anteport-guild-treck.jpg','map' => 'Straits of Devastation','way_point' => 'Lone Post Waypoint','cnname' => '','code' => '[&BPcCAAA=]'),
array('name' => 'Wassa\'s Terrace','pic_url' => 'gw2-wassas-terrace-guild-treck.jpg','map' => 'Gendarran Fields','way_point' => 'First Haven Waypoint','cnname' => '','code' => '[&BIsBAAA=]'),
array('name' => 'Watchpoint Decimus','pic_url' => 'gw2-watchpoint-decimus-guild-treck.jpg','map' => 'Plains of Ashford','way_point' => 'Guardpoint Decimus Waypoint','cnname' => '','code' => '[&BJgDAAA=]'),
array('name' => 'Wheelport Pub','pic_url' => 'gw2-wheelport-pub-guild-treck.jpg','map' => 'Black Citadel','way_point' => 'Mustering Ground Waypoint','cnname' => '','code' => '[&BKUDAAA=]'),
array('name' => 'Whitland Sinkhole','pic_url' => 'gw2-whitland-sinkhole-guild-treck.jpg','map' => 'Mount Maelstrom','way_point' => 'Old Sledge Site Waypoint','cnname' => '','code' => '[&BNQCAAA=]'),
array('name' => 'Widd’s Folly','pic_url' => 'gw2-widds-folly-guild-treck.jpg','map' => 'Caledon Forest','way_point' => 'Mabon Waypoint','cnname' => '','code' => '[&BDoBAAA=]'),
array('name' => 'Wikk\'s Gate','pic_url' => 'gw2-wikks-gate-guild-treck.jpg','map' => 'Timberline Falls','way_point' => 'Valance Tutory Waypoint','cnname' => '','code' => '[&BEwCAAA=]'),
array('name' => 'Wildflame Monitor','pic_url' => 'gw2-wildflame-monitor-guild-treck.jpg','map' => 'Metrica Province','way_point' => 'Soren Draa Waypoint','cnname' => '','code' => '[&BEAAAAA=]'),
array('name' => 'Winterknell Impasse','pic_url' => 'gw2-winterknell-impasse-guild-treck.jpg','map' => 'Cursed Shore','way_point' => 'R&D Waypoint','cnname' => '','code' => '[&BBgDAAA=]'),
array('name' => 'Wrelk’s Salon','pic_url' => 'gw2-wrelks-salon-guild-treck.jpg','map' => 'Gendarran Fields','way_point' => 'Almuten Waypoint','cnname' => '','code' => '[&BJQBAAA=]'),
);